### ISSUE TITLE
Configurable timestamps

### ISSUE THREAD

**Issue by deini** [chrisguttandin/dynamo-converters#79]
Would you be open to the idea of having some configuration options for `deltaToExpression`? 

I'm mostly interested in being able to configure the attribute names for  `created` and `modified`. Also their values to use `Date().toISOString()`.

**Comment by chrisguttandin** [comment]
Oh yes, I almost forgot about `marshal()`/`unmarshall()`. When I first heard about it I was thinking that I could deprecate this library now but I then realized that it's not really type safe and for some reason the package requires you to use lib dom which I don't really want when developing server-side code.

I meanwhile created a PR with the changes we discussed above. #80 Could you please take a look?

You can install the updated version like this:
```bash
npm i git://github.com/chrisguttandin/dynamo-converters.git#remove-timestamp-and-rename-export-build
```
