### ISSUE TITLE
Do we need here tslib, should we move it to "devDependency"

### ISSUE THREAD

**Issue by bartoszgolebiowski** [chrisguttandin/dynamo-converters#86]
https://github.com/search?q=repo%3Achrisguttandin%2Fdynamo-converters%20tslib&type=code

**Comment by chrisguttandin** [comment]
Yes, it's needed. It's an optional runtime dependency of TypeScript. It includes common code that may be used when TypeScript transpiles the source code to JavaScript. Of course, it only really makes sense if multiple modules use it.
